# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PalmReward' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PalmReward
pod 'VTMagic'
pod 'MJExtension', '~> 3.0.13'
pod 'AFNetworking', '~> 3.1.0'
pod 'RongCloudIMKit', '~> 2.7.3'
pod 'MJRefresh', '~> 3.1.12'
pod 'TZImagePickerController', '~> 1.7.1'
#pod 'MBProgressHUD', '~> 1.0.0'
pod 'DGActivityIndicatorView'
end
